# Generated by Django 3.2.8 on 2021-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211026_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='marks',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='AssignmentResult',
        ),
    ]
