# Generated by Django 3.2.8 on 2021-10-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_submissions_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='score',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
