# Generated by Django 3.2.8 on 2021-11-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assignment_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='report',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
